pull_request_rules:
  - name: add ci-passed when CI passed
    conditions:
      - check-success=lint-test
      - check-success=Broken Links
    actions:
      label:
        toggle:
          - ci-passed